const TV_DATA = [
  {Brand:"Samsung",Model:"QN85A",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:320,Star_Rating:3.5},
  {Brand:"Samsung",Model:"QN75A",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:260,Star_Rating:4.0},
  {Brand:"Samsung",Model:"QN65A",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:210,Star_Rating:4.5},
  {Brand:"Samsung",Model:"QN55A",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:160,Star_Rating:5.0},
  {Brand:"Samsung",Model:"QN50A",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:140,Star_Rating:5.0},
  {Brand:"Samsung",Model:"QN43A",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:110,Star_Rating:5.5},
  {Brand:"Samsung",Model:"QN32A",Screen_Tech:"LCD (LED)",Screen_Size:32,Power_Consumption:75,Star_Rating:6.0},
  {Brand:"Samsung",Model:"Q80A",Screen_Tech:"OLED",Screen_Size:65,Power_Consumption:200,Star_Rating:4.5},
  {Brand:"Samsung",Model:"Q70A",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:155,Star_Rating:5.0},
  {Brand:"Samsung",Model:"Q60A",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:135,Star_Rating:5.0},
  {Brand:"Samsung",Model:"Q50A",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:105,Star_Rating:5.5},
  {Brand:"Samsung",Model:"Q40A",Screen_Tech:"LCD (LED)",Screen_Size:32,Power_Consumption:70,Star_Rating:6.0},
  {Brand:"Samsung",Model:"UN85J",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:330,Star_Rating:3.5},
  {Brand:"Samsung",Model:"UN75J",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:265,Star_Rating:3.5},
  {Brand:"Samsung",Model:"UN65J",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:215,Star_Rating:4.0},
  {Brand:"Samsung",Model:"UN55J",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:165,Star_Rating:4.5},
  {Brand:"Samsung",Model:"UN50J",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:145,Star_Rating:5.0},
  {Brand:"Samsung",Model:"UN43J",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:115,Star_Rating:5.0},
  {Brand:"Samsung",Model:"UN32J",Screen_Tech:"LCD (LED)",Screen_Size:32,Power_Consumption:80,Star_Rating:5.5},
  {Brand:"Samsung",Model:"TU85",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:310,Star_Rating:3.5},
  {Brand:"Samsung",Model:"TU75",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:255,Star_Rating:4.0},
  {Brand:"Samsung",Model:"TU65",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:205,Star_Rating:4.5},
  {Brand:"Samsung",Model:"TU55",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:155,Star_Rating:5.0},
  {Brand:"Samsung",Model:"TU50",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:135,Star_Rating:5.0},
  {Brand:"Samsung",Model:"TU43",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:108,Star_Rating:5.5},
  {Brand:"LG",Model:"OLED83",Screen_Tech:"OLED",Screen_Size:83,Power_Consumption:290,Star_Rating:4.0},
  {Brand:"LG",Model:"OLED77",Screen_Tech:"OLED",Screen_Size:77,Power_Consumption:245,Star_Rating:4.5},
  {Brand:"LG",Model:"OLED65",Screen_Tech:"OLED",Screen_Size:65,Power_Consumption:195,Star_Rating:5.0},
  {Brand:"LG",Model:"OLED55",Screen_Tech:"OLED",Screen_Size:55,Power_Consumption:145,Star_Rating:5.5},
  {Brand:"LG",Model:"OLED48",Screen_Tech:"OLED",Screen_Size:48,Power_Consumption:120,Star_Rating:6.0},
  {Brand:"LG",Model:"OLED42",Screen_Tech:"OLED",Screen_Size:42,Power_Consumption:100,Star_Rating:6.0},
  {Brand:"LG",Model:"LED86",Screen_Tech:"LCD (LED)",Screen_Size:86,Power_Consumption:325,Star_Rating:3.5},
  {Brand:"LG",Model:"LED75",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:258,Star_Rating:4.0},
  {Brand:"LG",Model:"LED65",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:208,Star_Rating:4.5},
  {Brand:"LG",Model:"LED55",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:158,Star_Rating:5.0},
  {Brand:"LG",Model:"LED50",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:138,Star_Rating:5.0},
  {Brand:"LG",Model:"LED43",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:108,Star_Rating:5.5},
  {Brand:"LG",Model:"LED32",Screen_Tech:"LCD (LED)",Screen_Size:32,Power_Consumption:72,Star_Rating:6.0},
  {Brand:"LG",Model:"NANO86",Screen_Tech:"LCD (LED)",Screen_Size:86,Power_Consumption:318,Star_Rating:3.5},
  {Brand:"LG",Model:"NANO75",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:252,Star_Rating:4.0},
  {Brand:"LG",Model:"NANO65",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:202,Star_Rating:4.5},
  {Brand:"LG",Model:"NANO55",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:152,Star_Rating:5.0},
  {Brand:"LG",Model:"NANO50",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:132,Star_Rating:5.0},
  {Brand:"LG",Model:"NANO43",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:102,Star_Rating:5.5},
  {Brand:"LG",Model:"32LQ",Screen_Tech:"LCD",Screen_Size:32,Power_Consumption:68,Star_Rating:5.5},
  {Brand:"LG",Model:"28LQ",Screen_Tech:"LCD",Screen_Size:28,Power_Consumption:52,Star_Rating:6.0},
  {Brand:"LG",Model:"24LQ",Screen_Tech:"LCD",Screen_Size:24,Power_Consumption:42,Star_Rating:6.0},
  {Brand:"Hisense",Model:"85A7",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:315,Star_Rating:3.5},
  {Brand:"Hisense",Model:"75A7",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:255,Star_Rating:4.0},
  {Brand:"Hisense",Model:"65A7",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:200,Star_Rating:4.5},
  {Brand:"Hisense",Model:"55A7",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:152,Star_Rating:5.0},
  {Brand:"Hisense",Model:"50A7",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:130,Star_Rating:5.0},
  {Brand:"Hisense",Model:"43A7",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:105,Star_Rating:5.5},
  {Brand:"Hisense",Model:"32A7",Screen_Tech:"LCD (LED)",Screen_Size:32,Power_Consumption:68,Star_Rating:5.5},
  {Brand:"Hisense",Model:"85U7",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:305,Star_Rating:3.5},
  {Brand:"Hisense",Model:"75U7",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:248,Star_Rating:4.0},
  {Brand:"Hisense",Model:"65U7",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:195,Star_Rating:4.5},
  {Brand:"Hisense",Model:"55U7",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:148,Star_Rating:5.0},
  {Brand:"Hisense",Model:"50U7",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:128,Star_Rating:5.0},
  {Brand:"Hisense",Model:"43U7",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:102,Star_Rating:5.5},
  {Brand:"Hisense",Model:"85A6",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:320,Star_Rating:3.0},
  {Brand:"Hisense",Model:"75A6",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:260,Star_Rating:3.5},
  {Brand:"Hisense",Model:"65A6",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:205,Star_Rating:4.0},
  {Brand:"Hisense",Model:"55A6",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:155,Star_Rating:4.5},
  {Brand:"Hisense",Model:"50A6",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:133,Star_Rating:5.0},
  {Brand:"Hisense",Model:"43A6",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:107,Star_Rating:5.5},
  {Brand:"Hisense",Model:"32A6",Screen_Tech:"LCD (LED)",Screen_Size:32,Power_Consumption:70,Star_Rating:5.5},
  {Brand:"Sony",Model:"XR85X9",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:322,Star_Rating:3.5},
  {Brand:"Sony",Model:"XR75X9",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:262,Star_Rating:4.0},
  {Brand:"Sony",Model:"XR65X9",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:212,Star_Rating:4.5},
  {Brand:"Sony",Model:"XR55X9",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:162,Star_Rating:5.0},
  {Brand:"Sony",Model:"XR48X9",Screen_Tech:"LCD (LED)",Screen_Size:48,Power_Consumption:125,Star_Rating:5.0},
  {Brand:"Sony",Model:"A95K65",Screen_Tech:"OLED",Screen_Size:65,Power_Consumption:198,Star_Rating:5.0},
  {Brand:"Sony",Model:"A95K55",Screen_Tech:"OLED",Screen_Size:55,Power_Consumption:148,Star_Rating:5.5},
  {Brand:"Sony",Model:"A80K65",Screen_Tech:"OLED",Screen_Size:65,Power_Consumption:192,Star_Rating:5.0},
  {Brand:"Sony",Model:"A80K55",Screen_Tech:"OLED",Screen_Size:55,Power_Consumption:142,Star_Rating:5.5},
  {Brand:"Sony",Model:"A80K48",Screen_Tech:"OLED",Screen_Size:48,Power_Consumption:115,Star_Rating:6.0},
  {Brand:"Sony",Model:"XR85X8",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:318,Star_Rating:3.5},
  {Brand:"Sony",Model:"XR75X8",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:258,Star_Rating:4.0},
  {Brand:"Sony",Model:"XR65X8",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:208,Star_Rating:4.5},
  {Brand:"Sony",Model:"XR55X8",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:158,Star_Rating:5.0},
  {Brand:"TCL",Model:"85C7",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:308,Star_Rating:3.5},
  {Brand:"TCL",Model:"75C7",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:248,Star_Rating:4.0},
  {Brand:"TCL",Model:"65C7",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:196,Star_Rating:4.5},
  {Brand:"TCL",Model:"55C7",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:148,Star_Rating:5.0},
  {Brand:"TCL",Model:"50C7",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:126,Star_Rating:5.0},
  {Brand:"TCL",Model:"43C7",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:100,Star_Rating:5.5},
  {Brand:"TCL",Model:"32C7",Screen_Tech:"LCD (LED)",Screen_Size:32,Power_Consumption:66,Star_Rating:5.5},
  {Brand:"TCL",Model:"85P7",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:312,Star_Rating:3.5},
  {Brand:"TCL",Model:"75P7",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:252,Star_Rating:4.0},
  {Brand:"TCL",Model:"65P7",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:200,Star_Rating:4.5},
  {Brand:"TCL",Model:"55P7",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:150,Star_Rating:5.0},
  {Brand:"TCL",Model:"50P7",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:128,Star_Rating:5.0},
  {Brand:"TCL",Model:"43P7",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:102,Star_Rating:5.5},
  {Brand:"Panasonic",Model:"TH85",Screen_Tech:"LCD (LED)",Screen_Size:85,Power_Consumption:318,Star_Rating:3.5},
  {Brand:"Panasonic",Model:"TH75",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:255,Star_Rating:4.0},
  {Brand:"Panasonic",Model:"TH65",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:205,Star_Rating:4.5},
  {Brand:"Panasonic",Model:"TH55",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:155,Star_Rating:5.0},
  {Brand:"Panasonic",Model:"TH43",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:105,Star_Rating:5.5},
  {Brand:"Panasonic",Model:"TH32",Screen_Tech:"LCD (LED)",Screen_Size:32,Power_Consumption:69,Star_Rating:5.5},
  {Brand:"Panasonic",Model:"HZ2000",Screen_Tech:"OLED",Screen_Size:65,Power_Consumption:196,Star_Rating:5.0},
  {Brand:"Panasonic",Model:"HZ1500",Screen_Tech:"OLED",Screen_Size:55,Power_Consumption:146,Star_Rating:5.5},
  {Brand:"Panasonic",Model:"JZ2000",Screen_Tech:"OLED",Screen_Size:65,Power_Consumption:192,Star_Rating:5.0},
  {Brand:"Panasonic",Model:"JZ1500",Screen_Tech:"OLED",Screen_Size:55,Power_Consumption:142,Star_Rating:5.5},
  {Brand:"Philips",Model:"86PUS",Screen_Tech:"LCD (LED)",Screen_Size:86,Power_Consumption:320,Star_Rating:3.5},
  {Brand:"Philips",Model:"75PUS",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:258,Star_Rating:4.0},
  {Brand:"Philips",Model:"65PUS",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:205,Star_Rating:4.5},
  {Brand:"Philips",Model:"55PUS",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:155,Star_Rating:5.0},
  {Brand:"Philips",Model:"50PUS",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:132,Star_Rating:5.0},
  {Brand:"Philips",Model:"43PUS",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:105,Star_Rating:5.5},
  {Brand:"Philips",Model:"32PFS",Screen_Tech:"LCD",Screen_Size:32,Power_Consumption:65,Star_Rating:5.5},
  {Brand:"Philips",Model:"24PFS",Screen_Tech:"LCD",Screen_Size:24,Power_Consumption:40,Star_Rating:6.0},
  {Brand:"Kogan",Model:"86LED",Screen_Tech:"LCD (LED)",Screen_Size:86,Power_Consumption:325,Star_Rating:3.0},
  {Brand:"Kogan",Model:"75LED",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:262,Star_Rating:3.5},
  {Brand:"Kogan",Model:"65LED",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:210,Star_Rating:4.0},
  {Brand:"Kogan",Model:"55LED",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:160,Star_Rating:4.5},
  {Brand:"Kogan",Model:"50LED",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:138,Star_Rating:4.5},
  {Brand:"Kogan",Model:"43LED",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:110,Star_Rating:5.0},
  {Brand:"Kogan",Model:"32LED",Screen_Tech:"LCD (LED)",Screen_Size:32,Power_Consumption:72,Star_Rating:5.5},
  {Brand:"Kogan",Model:"24LED",Screen_Tech:"LCD",Screen_Size:24,Power_Consumption:44,Star_Rating:5.5},
  {Brand:"Sharp",Model:"70LC",Screen_Tech:"LCD (LED)",Screen_Size:70,Power_Consumption:238,Star_Rating:4.0},
  {Brand:"Sharp",Model:"60LC",Screen_Tech:"LCD (LED)",Screen_Size:60,Power_Consumption:188,Star_Rating:4.5},
  {Brand:"Sharp",Model:"55LC",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:153,Star_Rating:5.0},
  {Brand:"Sharp",Model:"50LC",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:130,Star_Rating:5.0},
  {Brand:"Sharp",Model:"43LC",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:103,Star_Rating:5.5},
  {Brand:"Sharp",Model:"32LC",Screen_Tech:"LCD",Screen_Size:32,Power_Consumption:66,Star_Rating:5.5},
  {Brand:"Sharp",Model:"24LC",Screen_Tech:"LCD",Screen_Size:24,Power_Consumption:41,Star_Rating:6.0},
  {Brand:"Haier",Model:"75H",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:255,Star_Rating:3.5},
  {Brand:"Haier",Model:"65H",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:205,Star_Rating:4.0},
  {Brand:"Haier",Model:"55H",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:155,Star_Rating:4.5},
  {Brand:"Haier",Model:"50H",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:133,Star_Rating:5.0},
  {Brand:"Haier",Model:"43H",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:105,Star_Rating:5.0},
  {Brand:"Haier",Model:"32H",Screen_Tech:"LCD",Screen_Size:32,Power_Consumption:68,Star_Rating:5.5},
  {Brand:"Skyworth",Model:"75S",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:252,Star_Rating:3.5},
  {Brand:"Skyworth",Model:"65S",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:202,Star_Rating:4.0},
  {Brand:"Skyworth",Model:"55S",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:152,Star_Rating:4.5},
  {Brand:"Skyworth",Model:"50S",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:130,Star_Rating:5.0},
  {Brand:"Skyworth",Model:"43S",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:103,Star_Rating:5.0},
  {Brand:"Skyworth",Model:"32S",Screen_Tech:"LCD",Screen_Size:32,Power_Consumption:66,Star_Rating:5.5},
  {Brand:"JVC",Model:"65JVC",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:200,Star_Rating:4.0},
  {Brand:"JVC",Model:"55JVC",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:150,Star_Rating:4.5},
  {Brand:"JVC",Model:"50JVC",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:128,Star_Rating:5.0},
  {Brand:"JVC",Model:"43JVC",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:102,Star_Rating:5.0},
  {Brand:"JVC",Model:"32JVC",Screen_Tech:"LCD",Screen_Size:32,Power_Consumption:65,Star_Rating:5.5},
  {Brand:"Toshiba",Model:"75TL",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:253,Star_Rating:3.5},
  {Brand:"Toshiba",Model:"65TL",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:200,Star_Rating:4.0},
  {Brand:"Toshiba",Model:"55TL",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:151,Star_Rating:4.5},
  {Brand:"Toshiba",Model:"50TL",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:129,Star_Rating:5.0},
  {Brand:"Toshiba",Model:"43TL",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:103,Star_Rating:5.0},
  {Brand:"Toshiba",Model:"32TL",Screen_Tech:"LCD",Screen_Size:32,Power_Consumption:66,Star_Rating:5.5},
  {Brand:"Vizio",Model:"75V",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:256,Star_Rating:3.5},
  {Brand:"Vizio",Model:"65V",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:204,Star_Rating:4.0},
  {Brand:"Vizio",Model:"55V",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:154,Star_Rating:4.5},
  {Brand:"Vizio",Model:"50V",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:131,Star_Rating:5.0},
  {Brand:"Vizio",Model:"43V",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:104,Star_Rating:5.0},
  {Brand:"Vizio",Model:"32V",Screen_Tech:"LCD",Screen_Size:32,Power_Consumption:67,Star_Rating:5.5},
  {Brand:"Xiaomi",Model:"75MI",Screen_Tech:"LCD (LED)",Screen_Size:75,Power_Consumption:252,Star_Rating:4.0},
  {Brand:"Xiaomi",Model:"65MI",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:200,Star_Rating:4.5},
  {Brand:"Xiaomi",Model:"55MI",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:150,Star_Rating:5.0},
  {Brand:"Xiaomi",Model:"50MI",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:128,Star_Rating:5.0},
  {Brand:"Xiaomi",Model:"43MI",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:102,Star_Rating:5.5},
  {Brand:"Xiaomi",Model:"32MI",Screen_Tech:"LCD",Screen_Size:32,Power_Consumption:65,Star_Rating:5.5},
  {Brand:"Soniq",Model:"65SQ",Screen_Tech:"LCD (LED)",Screen_Size:65,Power_Consumption:202,Star_Rating:4.0},
  {Brand:"Soniq",Model:"55SQ",Screen_Tech:"LCD (LED)",Screen_Size:55,Power_Consumption:153,Star_Rating:4.5},
  {Brand:"Soniq",Model:"50SQ",Screen_Tech:"LCD (LED)",Screen_Size:50,Power_Consumption:130,Star_Rating:5.0},
  {Brand:"Soniq",Model:"43SQ",Screen_Tech:"LCD (LED)",Screen_Size:43,Power_Consumption:104,Star_Rating:5.0},
  {Brand:"Soniq",Model:"32SQ",Screen_Tech:"LCD",Screen_Size:32,Power_Consumption:67,Star_Rating:5.5}
];
